# Generated by Django 6.0.7 on 2026-08-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_leave'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_employee_attendance_per_day',
        ),
    ]
